"""create readers table

Revision ID: 0e8e28a9f01c
Revises: 
Create Date: 2026-09-26 05:39:10.595197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e8e28a9f01c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('ticket_number', sa.String(length=32), nullable=True),
    sa.Column('ticket_status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('ticket_issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ticket_confiscated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confiscation_reason', sa.String(length=255), nullable=True),
    sa.Column('books_on_hand', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("ticket_status IN ('active', 'suspended', 'revoked')", name=op.f('ck_readers_ticket_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readers')),
    sa.UniqueConstraint('ticket_number', name=op.f('uq_readers_ticket_number'))
    )
    op.create_index('ix_readers_full_name', 'readers', ['full_name'], unique=False)
    # GIN-индекс по JSONB: ускоряет фильтры/отчёты с jsonb_path_exists.
    op.execute(
        "CREATE INDEX ix_readers_books_on_hand_gin ON readers "
        "USING GIN (books_on_hand jsonb_path_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_readers_books_on_hand_gin', table_name='readers')
    op.drop_index('ix_readers_full_name', table_name='readers')
    op.drop_table('readers')
    # ### end Alembic commands ###
